// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDXuGjZXDuhz-MfpmXnV6aGyOZuDKwYW10',
      appId: '1:788899673990:android:8bf8d872924706a6ce1e07',
      messagingSenderId: '788899673990',
      projectId: 'easy-date-dev',
      storageBucket: 'easy-date-dev.appspot.com',
      databaseURL:
          'https://easy-date-dev-default-rtdb.asia-southeast1.firebasedatabase.app');
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKeGl6TXqmet0kVANPQgUvjIBmFHb3FEw',
    appId: '1:788899673990:ios:1346a9e9901894adce1e07',
    messagingSenderId: '788899673990',
    projectId: 'easy-date-dev',
    storageBucket: 'easy-date-dev.appspot.com',
  );
}
