// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String ASSETS_FONTS_NUNITOSANS_BOLD_TTF =
      'assets/fonts/NunitoSans-Bold.ttf';

  static const String ASSETS_FONTS_NUNITOSANS_EXTRABOLD_TTF =
      'assets/fonts/NunitoSans-ExtraBold.ttf';

  static const String ASSETS_FONTS_NUNITOSANS_REGULAR_TTF =
      'assets/fonts/NunitoSans-Regular.ttf';

  static const String ASSETS_FONTS_NUNITOSANS_SEMIBOLD_TTF =
      'assets/fonts/NunitoSans-SemiBold.ttf';

  /// {@macro assets_generator.ASSETS_ICONS_APP_ICON2_SVG.preview}
  static const String ASSETS_ICONS_APP_ICON2_SVG = 'assets/icons/app_icon2.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_USER_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_ADD_USER_SELECTED_SVG =
      'assets/icons/ic_add_user_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_USER_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_ADD_USER_UNSELECTED_SVG =
      'assets/icons/ic_add_user_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_BLOCK_SVG.preview}
  static const String ASSETS_ICONS_IC_BLOCK_SVG = 'assets/icons/ic_block.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CHAT_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_CHAT_SELECTED_SVG =
      'assets/icons/ic_chat_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CHAT_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_CHAT_UNSELECTED_SVG =
      'assets/icons/ic_chat_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_HOME_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_HOME_SELECTED_SVG =
      'assets/icons/ic_home_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_HOME_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_HOME_UNSELECTED_SVG =
      'assets/icons/ic_home_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOCATION_SVG.preview}
  static const String ASSETS_ICONS_IC_LOCATION_SVG =
      'assets/icons/ic_location.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_PROFILE_SELECTED_SVG =
      'assets/icons/ic_profile_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_PROFILE_UNSELECTED_SVG =
      'assets/icons/ic_profile_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CLOSE_SVG.preview}
  static const String ASSETS_ICONS_ICON_CLOSE_SVG =
      'assets/icons/icon_close.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LIST_NULL_SVG.preview}
  static const String ASSETS_ICONS_ICON_LIST_NULL_SVG =
      'assets/icons/icon_list_null.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_MAP_SVG.preview}
  static const String ASSETS_ICONS_ICON_MAP_SVG = 'assets/icons/icon_map.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_TYM_SVG.preview}
  static const String ASSETS_ICONS_ICON_TYM_SVG = 'assets/icons/icon_tym.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_APP_ICON_PNG.preview}
  static const String ASSETS_IMAGES_APP_ICON_PNG = 'assets/images/app_icon.png';

  /// {@macro assets_generator.ASSETS_IMAGES_BG_HOME_GIF.preview}
  static const String ASSETS_IMAGES_BG_HOME_GIF = 'assets/images/bg_home.gif';

  /// {@macro assets_generator.ASSETS_IMAGES_BG_LOGIN_PNG.preview}
  static const String ASSETS_IMAGES_BG_LOGIN_PNG = 'assets/images/bg_login.png';

  /// {@macro assets_generator.ASSETS_IMAGES_CHAT_BACKGROUND_PNG.preview}
  static const String ASSETS_IMAGES_CHAT_BACKGROUND_PNG =
      'assets/images/chat_background.png';

  /// {@macro assets_generator.ASSETS_IMAGES_CHAT_LOVE_ICON_PNG.preview}
  static const String ASSETS_IMAGES_CHAT_LOVE_ICON_PNG =
      'assets/images/chat_love_icon.png';

  /// {@macro assets_generator.ASSETS_IMAGES_DUCK_JPG.preview}
  static const String ASSETS_IMAGES_DUCK_JPG = 'assets/images/duck.jpg';

  /// {@macro assets_generator.ASSETS_IMAGES_HEART_PNG.preview}
  static const String ASSETS_IMAGES_HEART_PNG = 'assets/images/heart.png';

  /// {@macro assets_generator.ASSETS_IMAGES_LOVE__PNG.preview}
  static const String ASSETS_IMAGES_LOVE__PNG = 'assets/images/love .png';

  /// {@macro assets_generator.ASSETS_IMAGES_LOVE_ANMATION_ICON_GIF.preview}
  static const String ASSETS_IMAGES_LOVE_ANMATION_ICON_GIF =
      'assets/images/love_anmation_icon.gif';

  /// {@macro assets_generator.ASSETS_IMAGES_LOVE_SUGGEST_ICON_PNG.preview}
  static const String ASSETS_IMAGES_LOVE_SUGGEST_ICON_PNG =
      'assets/images/love_suggest_icon.png';

  /// {@macro assets_generator.ASSETS_IMAGES_PLACE_GIF.preview}
  static const String ASSETS_IMAGES_PLACE_GIF = 'assets/images/place.gif';

  /// {@macro assets_generator.ASSETS_IMAGES_PLACE_PNG.preview}
  static const String ASSETS_IMAGES_PLACE_PNG = 'assets/images/place.png';
}
