import '../album_sticker.dart';
import '../sticker.dart';

const caveAlbum = AlbumSticker(
  id: "v6H7yXQ",
  isDefault: true,
  stickers: [
    Sticker(
      id: "rhIQ4w6",
      type: "image/png",
      animated: false,
      width: 105,
      height: 110,
      link: "https://i.imgur.com/rhIQ4w6.png",
    ),
    Sticker(
      id: "M6QpDyr",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/M6QpDyr.png",
    ),
    Sticker(
      id: "PDOtKXb",
      type: "image/png",
      animated: false,
      width: 104,
      height: 110,
      link: "https://i.imgur.com/PDOtKXb.png",
    ),
    Sticker(
      id: "xcRb5RV",
      type: "image/png",
      animated: false,
      width: 152,
      height: 110,
      link: "https://i.imgur.com/xcRb5RV.png",
    ),
    Sticker(
      id: "pJW7BVv",
      type: "image/png",
      animated: false,
      width: 143,
      height: 110,
      link: "https://i.imgur.com/pJW7BVv.png",
    ),
    Sticker(
      id: "zcJzjdC",
      type: "image/png",
      animated: false,
      width: 96,
      height: 110,
      link: "https://i.imgur.com/zcJzjdC.png",
    ),
    Sticker(
      id: "QRuNxz7",
      type: "image/png",
      animated: false,
      width: 103,
      height: 110,
      link: "https://i.imgur.com/QRuNxz7.png",
    ),
    Sticker(
      id: "HuERXUW",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/HuERXUW.png",
    ),
    Sticker(
      id: "gv02Aaw",
      type: "image/png",
      animated: false,
      width: 147,
      height: 110,
      link: "https://i.imgur.com/gv02Aaw.png",
    ),
    Sticker(
      id: "ITRq0be",
      type: "image/png",
      animated: false,
      width: 116,
      height: 110,
      link: "https://i.imgur.com/ITRq0be.png",
    ),
    Sticker(
      id: "n2C79yT",
      type: "image/png",
      animated: false,
      width: 115,
      height: 110,
      link: "https://i.imgur.com/n2C79yT.png",
    ),
    Sticker(
      id: "UXfYO53",
      type: "image/png",
      animated: false,
      width: 134,
      height: 110,
      link: "https://i.imgur.com/UXfYO53.png",
    ),
    Sticker(
      id: "duhPt8D",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/duhPt8D.png",
    ),
    Sticker(
      id: "fAZ8cP5",
      type: "image/png",
      animated: false,
      width: 134,
      height: 110,
      link: "https://i.imgur.com/fAZ8cP5.png",
    ),
    Sticker(
      id: "EhaVbRO",
      type: "image/png",
      animated: false,
      width: 134,
      height: 110,
      link: "https://i.imgur.com/EhaVbRO.png",
    ),
    Sticker(
      id: "oigxFuN",
      type: "image/png",
      animated: false,
      width: 124,
      height: 110,
      link: "https://i.imgur.com/oigxFuN.png",
    ),
    Sticker(
      id: "vJ48G23",
      type: "image/png",
      animated: false,
      width: 117,
      height: 110,
      link: "https://i.imgur.com/vJ48G23.png",
    ),
    Sticker(
      id: "WjHgTVC",
      type: "image/png",
      animated: false,
      width: 136,
      height: 110,
      link: "https://i.imgur.com/WjHgTVC.png",
    ),
    Sticker(
      id: "hwlV2Zs",
      type: "image/png",
      animated: false,
      width: 108,
      height: 110,
      link: "https://i.imgur.com/hwlV2Zs.png",
    ),
    Sticker(
      id: "RMBjjLn",
      type: "image/png",
      animated: false,
      width: 139,
      height: 110,
      link: "https://i.imgur.com/RMBjjLn.png",
    ),
    Sticker(
      id: "4HC0KAY",
      type: "image/png",
      animated: false,
      width: 133,
      height: 110,
      link: "https://i.imgur.com/4HC0KAY.png",
    ),
    Sticker(
      id: "UKXAWar",
      type: "image/png",
      animated: false,
      width: 112,
      height: 110,
      link: "https://i.imgur.com/UKXAWar.png",
    ),
    Sticker(
      id: "4iDGwAg",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/4iDGwAg.png",
    ),
    Sticker(
      id: "pUeB2Ss",
      type: "image/png",
      animated: false,
      width: 117,
      height: 110,
      link: "https://i.imgur.com/pUeB2Ss.png",
    ),
    Sticker(
      id: "Uf0xsAQ",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/Uf0xsAQ.png",
    ),
    Sticker(
      id: "x6QM7e5",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/x6QM7e5.png",
    ),
    Sticker(
      id: "EnUHLDC",
      type: "image/png",
      animated: false,
      width: 134,
      height: 110,
      link: "https://i.imgur.com/EnUHLDC.png",
    ),
    Sticker(
      id: "TSNSBDj",
      type: "image/png",
      animated: false,
      width: 138,
      height: 110,
      link: "https://i.imgur.com/TSNSBDj.png",
    ),
    Sticker(
      id: "UmXOC3V",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/UmXOC3V.png",
    ),
    Sticker(
      id: "KBTj8Up",
      type: "image/png",
      animated: false,
      width: 116,
      height: 110,
      link: "https://i.imgur.com/KBTj8Up.png",
    ),
    Sticker(
      id: "NRCuoPV",
      type: "image/png",
      animated: false,
      width: 126,
      height: 110,
      link: "https://i.imgur.com/NRCuoPV.png",
    ),
    Sticker(
      id: "LUkzlrQ",
      type: "image/png",
      animated: false,
      width: 137,
      height: 110,
      link: "https://i.imgur.com/LUkzlrQ.png",
    ),
    Sticker(
      id: "PHRaKh5",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/PHRaKh5.png",
    ),
    Sticker(
      id: "K2heGah",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/K2heGah.png",
    ),
    Sticker(
      id: "Go5Q1bI",
      type: "image/png",
      animated: false,
      width: 132,
      height: 110,
      link: "https://i.imgur.com/Go5Q1bI.png",
    ),
    Sticker(
      id: "GFd0ncp",
      type: "image/png",
      animated: false,
      width: 133,
      height: 110,
      link: "https://i.imgur.com/GFd0ncp.png",
    ),
    Sticker(
      id: "hwYPC81",
      type: "image/png",
      animated: false,
      width: 130,
      height: 110,
      link: "https://i.imgur.com/hwYPC81.png",
    ),
    Sticker(
      id: "bgHwTrk",
      type: "image/png",
      animated: false,
      width: 130,
      height: 110,
      link: "https://i.imgur.com/bgHwTrk.png",
    ),
    Sticker(
      id: "CaQwg08",
      type: "image/png",
      animated: false,
      width: 132,
      height: 110,
      link: "https://i.imgur.com/CaQwg08.png",
    ),
    Sticker(
      id: "OZhiYJA",
      type: "image/png",
      animated: false,
      width: 110,
      height: 110,
      link: "https://i.imgur.com/OZhiYJA.png",
    ),
    Sticker(
      id: "fGEiUPT",
      type: "image/png",
      animated: false,
      width: 138,
      height: 110,
      link: "https://i.imgur.com/fGEiUPT.png",
    ),
    Sticker(
      id: "KgsOMmJ",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/KgsOMmJ.png",
    ),
    Sticker(
      id: "2Xd2T6R",
      type: "image/png",
      animated: false,
      width: 98,
      height: 110,
      link: "https://i.imgur.com/2Xd2T6R.png",
    ),
    Sticker(
      id: "LBO16Js",
      type: "image/png",
      animated: false,
      width: 121,
      height: 110,
      link: "https://i.imgur.com/LBO16Js.png",
    ),
    Sticker(
      id: "gozixSg",
      type: "image/png",
      animated: false,
      width: 156,
      height: 110,
      link: "https://i.imgur.com/gozixSg.png",
    ),
    Sticker(
      id: "7trFHDi",
      type: "image/png",
      animated: false,
      width: 110,
      height: 110,
      link: "https://i.imgur.com/7trFHDi.png",
    ),
    Sticker(
      id: "AXBXPkO",
      type: "image/png",
      animated: false,
      width: 111,
      height: 110,
      link: "https://i.imgur.com/AXBXPkO.png",
    ),
    Sticker(
      id: "lUEMDBU",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/lUEMDBU.png",
    ),
    Sticker(
      id: "PWFKc3D",
      type: "image/png",
      animated: false,
      width: 133,
      height: 110,
      link: "https://i.imgur.com/PWFKc3D.png",
    ),
    Sticker(
      id: "YZ6HeFQ",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/YZ6HeFQ.png",
    ),
    Sticker(
      id: "PiNPcY2",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/PiNPcY2.png",
    ),
    Sticker(
      id: "o81SQii",
      type: "image/png",
      animated: false,
      width: 138,
      height: 110,
      link: "https://i.imgur.com/o81SQii.png",
    ),
    Sticker(
      id: "8EN66AK",
      type: "image/png",
      animated: false,
      width: 138,
      height: 110,
      link: "https://i.imgur.com/8EN66AK.png",
    ),
    Sticker(
      id: "9euXh0b",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/9euXh0b.png",
    ),
    Sticker(
      id: "mikGycI",
      type: "image/png",
      animated: false,
      width: 134,
      height: 110,
      link: "https://i.imgur.com/mikGycI.png",
    ),
    Sticker(
      id: "7EltOlq",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/7EltOlq.png",
    ),
    Sticker(
      id: "cxjDtPz",
      type: "image/png",
      animated: false,
      width: 132,
      height: 110,
      link: "https://i.imgur.com/cxjDtPz.png",
    ),
    Sticker(
      id: "EZGNxyw",
      type: "image/png",
      animated: false,
      width: 136,
      height: 110,
      link: "https://i.imgur.com/EZGNxyw.png",
    ),
    Sticker(
      id: "ajqN7O2",
      type: "image/png",
      animated: false,
      width: 130,
      height: 110,
      link: "https://i.imgur.com/ajqN7O2.png",
    ),
    Sticker(
      id: "0LjbkWw",
      type: "image/png",
      animated: false,
      width: 137,
      height: 110,
      link: "https://i.imgur.com/0LjbkWw.png",
    ),
    Sticker(
      id: "xKgiPmO",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/xKgiPmO.png",
    ),
    Sticker(
      id: "UMqPdXs",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/UMqPdXs.png",
    ),
    Sticker(
      id: "EXM6zxn",
      type: "image/png",
      animated: false,
      width: 138,
      height: 110,
      link: "https://i.imgur.com/EXM6zxn.png",
    ),
    Sticker(
      id: "gzt8PeJ",
      type: "image/png",
      animated: false,
      width: 114,
      height: 110,
      link: "https://i.imgur.com/gzt8PeJ.png",
    ),
    Sticker(
      id: "RZjqg0r",
      type: "image/png",
      animated: false,
      width: 157,
      height: 110,
      link: "https://i.imgur.com/RZjqg0r.png",
    ),
    Sticker(
      id: "LQ2KFXU",
      type: "image/png",
      animated: false,
      width: 156,
      height: 110,
      link: "https://i.imgur.com/LQ2KFXU.png",
    ),
    Sticker(
      id: "3oyj0s3",
      type: "image/png",
      animated: false,
      width: 121,
      height: 110,
      link: "https://i.imgur.com/3oyj0s3.png",
    ),
    Sticker(
      id: "srth3iS",
      type: "image/png",
      animated: false,
      width: 161,
      height: 110,
      link: "https://i.imgur.com/srth3iS.png",
    ),
    Sticker(
      id: "IDPD91q",
      type: "image/png",
      animated: false,
      width: 112,
      height: 110,
      link: "https://i.imgur.com/IDPD91q.png",
    ),
    Sticker(
      id: "xxRDqKM",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/xxRDqKM.png",
    ),
    Sticker(
      id: "YVLAaxb",
      type: "image/png",
      animated: false,
      width: 108,
      height: 110,
      link: "https://i.imgur.com/YVLAaxb.png",
    ),
    Sticker(
      id: "dKGpxwy",
      type: "image/png",
      animated: false,
      width: 121,
      height: 110,
      link: "https://i.imgur.com/dKGpxwy.png",
    ),
    Sticker(
      id: "AdpfqV5",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/AdpfqV5.png",
    ),
    Sticker(
      id: "jx2V6ei",
      type: "image/png",
      animated: false,
      width: 128,
      height: 110,
      link: "https://i.imgur.com/jx2V6ei.png",
    ),
    Sticker(
      id: "hLLENbU",
      type: "image/png",
      animated: false,
      width: 124,
      height: 110,
      link: "https://i.imgur.com/hLLENbU.png",
    ),
    Sticker(
      id: "Cx6vtzp",
      type: "image/png",
      animated: false,
      width: 138,
      height: 110,
      link: "https://i.imgur.com/Cx6vtzp.png",
    ),
    Sticker(
      id: "SP6lQZO",
      type: "image/png",
      animated: false,
      width: 133,
      height: 110,
      link: "https://i.imgur.com/SP6lQZO.png",
    ),
    Sticker(
      id: "r9TL23e",
      type: "image/png",
      animated: false,
      width: 194,
      height: 110,
      link: "https://i.imgur.com/r9TL23e.png",
    ),
    Sticker(
      id: "FZy1SfD",
      type: "image/png",
      animated: false,
      width: 117,
      height: 110,
      link: "https://i.imgur.com/FZy1SfD.png",
    ),
    Sticker(
      id: "Y8hl0fQ",
      type: "image/png",
      animated: false,
      width: 193,
      height: 110,
      link: "https://i.imgur.com/Y8hl0fQ.png",
    ),
    Sticker(
      id: "675QJW7",
      type: "image/png",
      animated: false,
      width: 138,
      height: 110,
      link: "https://i.imgur.com/675QJW7.png",
    ),
    Sticker(
      id: "royBRfN",
      type: "image/png",
      animated: false,
      width: 117,
      height: 110,
      link: "https://i.imgur.com/royBRfN.png",
    ),
    Sticker(
      id: "WjsCy44",
      type: "image/png",
      animated: false,
      width: 174,
      height: 110,
      link: "https://i.imgur.com/WjsCy44.png",
    ),
    Sticker(
      id: "mRV706L",
      type: "image/png",
      animated: false,
      width: 132,
      height: 110,
      link: "https://i.imgur.com/mRV706L.png",
    ),
    Sticker(
      id: "RAZ3ARY",
      type: "image/png",
      animated: false,
      width: 162,
      height: 110,
      link: "https://i.imgur.com/RAZ3ARY.png",
    ),
    Sticker(
      id: "g3R0KqI",
      type: "image/png",
      animated: false,
      width: 105,
      height: 110,
      link: "https://i.imgur.com/g3R0KqI.png",
    ),
    Sticker(
      id: "0p6NIQJ",
      type: "image/png",
      animated: false,
      width: 116,
      height: 110,
      link: "https://i.imgur.com/0p6NIQJ.png",
    ),
    Sticker(
      id: "D1Ycz7B",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/D1Ycz7B.png",
    ),
    Sticker(
      id: "3MbhzSA",
      type: "image/png",
      animated: false,
      width: 124,
      height: 110,
      link: "https://i.imgur.com/3MbhzSA.png",
    ),
    Sticker(
      id: "j6jQz01",
      type: "image/png",
      animated: false,
      width: 127,
      height: 110,
      link: "https://i.imgur.com/j6jQz01.png",
    ),
    Sticker(
      id: "N6DLt8Y",
      type: "image/png",
      animated: false,
      width: 99,
      height: 110,
      link: "https://i.imgur.com/N6DLt8Y.png",
    ),
    Sticker(
      id: "FwlHqNY",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/FwlHqNY.png",
    ),
    Sticker(
      id: "nICLz1p",
      type: "image/png",
      animated: false,
      width: 132,
      height: 110,
      link: "https://i.imgur.com/nICLz1p.png",
    ),
    Sticker(
      id: "VZoTTwf",
      type: "image/png",
      animated: false,
      width: 132,
      height: 110,
      link: "https://i.imgur.com/VZoTTwf.png",
    ),
    Sticker(
      id: "VInmq7p",
      type: "image/png",
      animated: false,
      width: 134,
      height: 110,
      link: "https://i.imgur.com/VInmq7p.png",
    ),
    Sticker(
      id: "xfA1IwK",
      type: "image/png",
      animated: false,
      width: 124,
      height: 110,
      link: "https://i.imgur.com/xfA1IwK.png",
    ),
    Sticker(
      id: "5KHLT3w",
      type: "image/png",
      animated: false,
      width: 142,
      height: 110,
      link: "https://i.imgur.com/5KHLT3w.png",
    ),
    Sticker(
      id: "ueH6FHa",
      type: "image/png",
      animated: false,
      width: 137,
      height: 110,
      link: "https://i.imgur.com/ueH6FHa.png",
    ),
    Sticker(
      id: "8NZ0U46",
      type: "image/png",
      animated: false,
      width: 131,
      height: 110,
      link: "https://i.imgur.com/8NZ0U46.png",
    ),
    Sticker(
      id: "9G8runF",
      type: "image/png",
      animated: false,
      width: 107,
      height: 110,
      link: "https://i.imgur.com/9G8runF.png",
    ),
    Sticker(
      id: "wHySFoA",
      type: "image/png",
      animated: false,
      width: 100,
      height: 93,
      link: "https://i.imgur.com/wHySFoA.png",
    ),
    Sticker(
      id: "8jua1oy",
      type: "image/png",
      animated: false,
      width: 100,
      height: 85,
      link: "https://i.imgur.com/8jua1oy.png",
    ),
    Sticker(
      id: "lurhyhV",
      type: "image/png",
      animated: false,
      width: 100,
      height: 91,
      link: "https://i.imgur.com/lurhyhV.png",
    ),
    Sticker(
      id: "VD3CBJi",
      type: "image/png",
      animated: false,
      width: 100,
      height: 83,
      link: "https://i.imgur.com/VD3CBJi.png",
    ),
    Sticker(
      id: "8RRNvWB",
      type: "image/png",
      animated: false,
      width: 100,
      height: 86,
      link: "https://i.imgur.com/8RRNvWB.png",
    ),
    Sticker(
      id: "l1gZInB",
      type: "image/png",
      animated: false,
      width: 100,
      height: 86,
      link: "https://i.imgur.com/l1gZInB.png",
    ),
    Sticker(
      id: "FZUTqcr",
      type: "image/png",
      animated: false,
      width: 100,
      height: 91,
      link: "https://i.imgur.com/FZUTqcr.png",
    ),
    Sticker(
      id: "wOlEykZ",
      type: "image/png",
      animated: false,
      width: 100,
      height: 88,
      link: "https://i.imgur.com/wOlEykZ.png",
    ),
    Sticker(
      id: "GzH92cF",
      type: "image/png",
      animated: false,
      width: 100,
      height: 83,
      link: "https://i.imgur.com/GzH92cF.png",
    ),
    Sticker(
      id: "LAbND8Z",
      type: "image/png",
      animated: false,
      width: 116,
      height: 100,
      link: "https://i.imgur.com/LAbND8Z.png",
    ),
  ],
);
