import '../album_sticker.dart';
import '../sticker.dart';

const doremonAlbum = AlbumSticker(
  id: "wb63m",
  isDefault: true,
  stickers: [
    Sticker(
      id: "nEFecFa",
      type: "image/png",
      animated: false,
      width: 106,
      height: 80,
      link: "https://i.imgur.com/nEFecFa.png",
    ),
    Sticker(
      id: "7TEsEzR",
      type: "image/png",
      animated: false,
      width: 70,
      height: 80,
      link: "https://i.imgur.com/7TEsEzR.png",
    ),
    Sticker(
      id: "N8tG58k",
      type: "image/png",
      animated: false,
      width: 67,
      height: 80,
      link: "https://i.imgur.com/N8tG58k.png",
    ),
    Sticker(
      id: "fGKMO1p",
      type: "image/png",
      animated: false,
      width: 74,
      height: 80,
      link: "https://i.imgur.com/fGKMO1p.png",
    ),
    Sticker(
      id: "59S2vtW",
      type: "image/png",
      animated: false,
      width: 82,
      height: 80,
      link: "https://i.imgur.com/59S2vtW.png",
    ),
    Sticker(
      id: "sW1yWQG",
      type: "image/png",
      animated: false,
      width: 107,
      height: 80,
      link: "https://i.imgur.com/sW1yWQG.png",
    ),
    Sticker(
      id: "g2D10hA",
      type: "image/png",
      animated: false,
      width: 107,
      height: 80,
      link: "https://i.imgur.com/g2D10hA.png",
    ),
    Sticker(
      id: "Vs4ZJOA",
      type: "image/png",
      animated: false,
      width: 72,
      height: 80,
      link: "https://i.imgur.com/Vs4ZJOA.png",
    ),
    Sticker(
      id: "lpXqlwW",
      type: "image/png",
      animated: false,
      width: 104,
      height: 80,
      link: "https://i.imgur.com/lpXqlwW.png",
    ),
    Sticker(
      id: "Xh5d3v5",
      type: "image/png",
      animated: false,
      width: 108,
      height: 80,
      link: "https://i.imgur.com/Xh5d3v5.png",
    ),
    Sticker(
      id: "sc9cajE",
      type: "image/png",
      animated: false,
      width: 75,
      height: 80,
      link: "https://i.imgur.com/sc9cajE.png",
    ),
    Sticker(
      id: "TKL2cck",
      type: "image/png",
      animated: false,
      width: 87,
      height: 80,
      link: "https://i.imgur.com/TKL2cck.png",
    ),
    Sticker(
      id: "lEc9Qfb",
      type: "image/png",
      animated: false,
      width: 82,
      height: 80,
      link: "https://i.imgur.com/lEc9Qfb.png",
    ),
    Sticker(
      id: "BYyva7z",
      type: "image/png",
      animated: false,
      width: 83,
      height: 80,
      link: "https://i.imgur.com/BYyva7z.png",
    ),
    Sticker(
      id: "cOZnTqW",
      type: "image/png",
      animated: false,
      width: 137,
      height: 80,
      link: "https://i.imgur.com/cOZnTqW.png",
    ),
    Sticker(
      id: "5RqFJEX",
      type: "image/png",
      animated: false,
      width: 67,
      height: 80,
      link: "https://i.imgur.com/5RqFJEX.png",
    ),
    Sticker(
      id: "FKBa3sg",
      type: "image/png",
      animated: false,
      width: 82,
      height: 80,
      link: "https://i.imgur.com/FKBa3sg.png",
    ),
    Sticker(
      id: "9OzTW1u",
      type: "image/png",
      animated: false,
      width: 95,
      height: 80,
      link: "https://i.imgur.com/9OzTW1u.png",
    ),
    Sticker(
      id: "YMk8lBu",
      type: "image/png",
      animated: false,
      width: 90,
      height: 80,
      link: "https://i.imgur.com/YMk8lBu.png",
    ),
    Sticker(
      id: "b84UnA6",
      type: "image/png",
      animated: false,
      width: 91,
      height: 80,
      link: "https://i.imgur.com/b84UnA6.png",
    ),
    Sticker(
      id: "dPLRKNT",
      type: "image/png",
      animated: false,
      width: 100,
      height: 80,
      link: "https://i.imgur.com/dPLRKNT.png",
    ),
    Sticker(
      id: "EQNTARg",
      type: "image/png",
      animated: false,
      width: 87,
      height: 80,
      link: "https://i.imgur.com/EQNTARg.png",
    ),
    Sticker(
      id: "Vsn3go3",
      type: "image/png",
      animated: false,
      width: 74,
      height: 80,
      link: "https://i.imgur.com/Vsn3go3.png",
    ),
    Sticker(
      id: "VZJfejo",
      type: "image/png",
      animated: false,
      width: 86,
      height: 80,
      link: "https://i.imgur.com/VZJfejo.png",
    ),
    Sticker(
      id: "GVbJdiz",
      type: "image/png",
      animated: false,
      width: 92,
      height: 80,
      link: "https://i.imgur.com/GVbJdiz.png",
    ),
    Sticker(
      id: "t9TATVT",
      type: "image/png",
      animated: false,
      width: 90,
      height: 80,
      link: "https://i.imgur.com/t9TATVT.png",
    ),
    Sticker(
      id: "qzlwUza",
      type: "image/png",
      animated: false,
      width: 75,
      height: 80,
      link: "https://i.imgur.com/qzlwUza.png",
    ),
    Sticker(
      id: "yh96EZf",
      type: "image/png",
      animated: false,
      width: 91,
      height: 80,
      link: "https://i.imgur.com/yh96EZf.png",
    ),
    Sticker(
      id: "6F1zOdm",
      type: "image/png",
      animated: false,
      width: 91,
      height: 80,
      link: "https://i.imgur.com/6F1zOdm.png",
    ),
    Sticker(
      id: "aZ1wUYX",
      type: "image/png",
      animated: false,
      width: 103,
      height: 80,
      link: "https://i.imgur.com/aZ1wUYX.png",
    ),
    Sticker(
      id: "xwJvOkL",
      type: "image/png",
      animated: false,
      width: 90,
      height: 80,
      link: "https://i.imgur.com/xwJvOkL.png",
    ),
    Sticker(
      id: "kURVISH",
      type: "image/png",
      animated: false,
      width: 79,
      height: 80,
      link: "https://i.imgur.com/kURVISH.png",
    ),
    Sticker(
      id: "6UeX0IG",
      type: "image/png",
      animated: false,
      width: 75,
      height: 80,
      link: "https://i.imgur.com/6UeX0IG.png",
    ),
    Sticker(
      id: "tuBz5ly",
      type: "image/png",
      animated: false,
      width: 109,
      height: 80,
      link: "https://i.imgur.com/tuBz5ly.png",
    ),
    Sticker(
      id: "sp62TZY",
      type: "image/png",
      animated: false,
      width: 94,
      height: 80,
      link: "https://i.imgur.com/sp62TZY.png",
    ),
    Sticker(
      id: "uGZPr0j",
      type: "image/png",
      animated: false,
      width: 79,
      height: 80,
      link: "https://i.imgur.com/uGZPr0j.png",
    ),
    Sticker(
      id: "NNJS4PR",
      type: "image/png",
      animated: false,
      width: 109,
      height: 80,
      link: "https://i.imgur.com/NNJS4PR.png",
    ),
    Sticker(
      id: "HhMiohV",
      type: "image/png",
      animated: false,
      width: 98,
      height: 80,
      link: "https://i.imgur.com/HhMiohV.png",
    ),
    Sticker(
      id: "Y9v1WcI",
      type: "image/png",
      animated: false,
      width: 102,
      height: 80,
      link: "https://i.imgur.com/Y9v1WcI.png",
    ),
    Sticker(
      id: "wE6RzgO",
      type: "image/png",
      animated: false,
      width: 121,
      height: 80,
      link: "https://i.imgur.com/wE6RzgO.png",
    ),
    Sticker(
      id: "fbagx87",
      type: "image/png",
      animated: false,
      width: 75,
      height: 80,
      link: "https://i.imgur.com/fbagx87.png",
    ),
    Sticker(
      id: "BV3l4ab",
      type: "image/png",
      animated: false,
      width: 95,
      height: 80,
      link: "https://i.imgur.com/BV3l4ab.png",
    ),
    Sticker(
      id: "ZuJsv1V",
      type: "image/png",
      animated: false,
      width: 105,
      height: 80,
      link: "https://i.imgur.com/ZuJsv1V.png",
    ),
    Sticker(
      id: "v63hS2x",
      type: "image/png",
      animated: false,
      width: 88,
      height: 80,
      link: "https://i.imgur.com/v63hS2x.png",
    ),
    Sticker(
      id: "pI7JltS",
      type: "image/png",
      animated: false,
      width: 96,
      height: 80,
      link: "https://i.imgur.com/pI7JltS.png",
    ),
    Sticker(
      id: "1afr8hX",
      type: "image/png",
      animated: false,
      width: 109,
      height: 80,
      link: "https://i.imgur.com/1afr8hX.png",
    ),
    Sticker(
      id: "KsxMEvz",
      type: "image/png",
      animated: false,
      width: 91,
      height: 80,
      link: "https://i.imgur.com/KsxMEvz.png",
    ),
    Sticker(
      id: "t799X4u",
      type: "image/png",
      animated: false,
      width: 69,
      height: 80,
      link: "https://i.imgur.com/t799X4u.png",
    ),
    Sticker(
      id: "hM1DyzN",
      type: "image/png",
      animated: false,
      width: 84,
      height: 80,
      link: "https://i.imgur.com/hM1DyzN.png",
    ),
    Sticker(
      id: "1OxmwMw",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/1OxmwMw.png",
    ),
    Sticker(
      id: "1K75l3O",
      type: "image/png",
      animated: false,
      width: 107,
      height: 80,
      link: "https://i.imgur.com/1K75l3O.png",
    ),
    Sticker(
      id: "Ps0wDFd",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/Ps0wDFd.png",
    ),
    Sticker(
      id: "zk3AXzs",
      type: "image/png",
      animated: false,
      width: 74,
      height: 80,
      link: "https://i.imgur.com/zk3AXzs.png",
    ),
    Sticker(
      id: "lGkYqVi",
      type: "image/png",
      animated: false,
      width: 109,
      height: 80,
      link: "https://i.imgur.com/lGkYqVi.png",
    ),
    Sticker(
      id: "gr26PD3",
      type: "image/png",
      animated: false,
      width: 95,
      height: 80,
      link: "https://i.imgur.com/gr26PD3.png",
    ),
    Sticker(
      id: "xSMMVEx",
      type: "image/png",
      animated: false,
      width: 109,
      height: 80,
      link: "https://i.imgur.com/xSMMVEx.png",
    ),
    Sticker(
      id: "p0Xv0i3",
      type: "image/png",
      animated: false,
      width: 92,
      height: 80,
      link: "https://i.imgur.com/p0Xv0i3.png",
    ),
    Sticker(
      id: "nVfwrsj",
      type: "image/png",
      animated: false,
      width: 88,
      height: 80,
      link: "https://i.imgur.com/nVfwrsj.png",
    ),
    Sticker(
      id: "an4FZWN",
      type: "image/png",
      animated: false,
      width: 73,
      height: 80,
      link: "https://i.imgur.com/an4FZWN.png",
    ),
    Sticker(
      id: "ONQziCc",
      type: "image/png",
      animated: false,
      width: 91,
      height: 80,
      link: "https://i.imgur.com/ONQziCc.png",
    ),
    Sticker(
      id: "HdruS0s",
      type: "image/png",
      animated: false,
      width: 126,
      height: 80,
      link: "https://i.imgur.com/HdruS0s.png",
    ),
    Sticker(
      id: "AMrHKAS",
      type: "image/png",
      animated: false,
      width: 85,
      height: 80,
      link: "https://i.imgur.com/AMrHKAS.png",
    ),
    Sticker(
      id: "DUGVBvg",
      type: "image/png",
      animated: false,
      width: 93,
      height: 80,
      link: "https://i.imgur.com/DUGVBvg.png",
    ),
    Sticker(
      id: "vRiNE0p",
      type: "image/png",
      animated: false,
      width: 71,
      height: 80,
      link: "https://i.imgur.com/vRiNE0p.png",
    ),
    Sticker(
      id: "LeiEkF9",
      type: "image/png",
      animated: false,
      width: 111,
      height: 80,
      link: "https://i.imgur.com/LeiEkF9.png",
    ),
    Sticker(
      id: "axS3UlL",
      type: "image/png",
      animated: false,
      width: 82,
      height: 80,
      link: "https://i.imgur.com/axS3UlL.png",
    ),
    Sticker(
      id: "exeS9Ea",
      type: "image/png",
      animated: false,
      width: 78,
      height: 80,
      link: "https://i.imgur.com/exeS9Ea.png",
    ),
    Sticker(
      id: "mVGrBr7",
      type: "image/png",
      animated: false,
      width: 84,
      height: 80,
      link: "https://i.imgur.com/mVGrBr7.png",
    ),
    Sticker(
      id: "tYQn6uQ",
      type: "image/png",
      animated: false,
      width: 79,
      height: 80,
      link: "https://i.imgur.com/tYQn6uQ.png",
    ),
    Sticker(
      id: "i8ZNneh",
      type: "image/png",
      animated: false,
      width: 83,
      height: 80,
      link: "https://i.imgur.com/i8ZNneh.png",
    ),
    Sticker(
      id: "fSVmHaz",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/fSVmHaz.png",
    ),
    Sticker(
      id: "8K23a9b",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/8K23a9b.png",
    ),
    Sticker(
      id: "ojcaM5b",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/ojcaM5b.png",
    ),
    Sticker(
      id: "wOBhiky",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/wOBhiky.png",
    ),
    Sticker(
      id: "2rSU4jo",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/2rSU4jo.png",
    ),
    Sticker(
      id: "2QuPov6",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/2QuPov6.png",
    ),
    Sticker(
      id: "2YOHd4f",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/2YOHd4f.png",
    ),
    Sticker(
      id: "Tbi4iH1",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/Tbi4iH1.png",
    ),
    Sticker(
      id: "ozjyem1",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/ozjyem1.png",
    ),
    Sticker(
      id: "DZ83bVx",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/DZ83bVx.png",
    ),
    Sticker(
      id: "V1aRwDI",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/V1aRwDI.png",
    ),
    Sticker(
      id: "m1qWXzI",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/m1qWXzI.png",
    ),
    Sticker(
      id: "pl3B0cg",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/pl3B0cg.png",
    ),
    Sticker(
      id: "67GBPj6",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/67GBPj6.png",
    ),
    Sticker(
      id: "KBiJPy5",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/KBiJPy5.png",
    ),
    Sticker(
      id: "0Pj3Zwh",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/0Pj3Zwh.png",
    ),
    Sticker(
      id: "OC2WuCj",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/OC2WuCj.png",
    ),
    Sticker(
      id: "waCcfOz",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/waCcfOz.png",
    ),
    Sticker(
      id: "NHIQZGo",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/NHIQZGo.png",
    ),
    Sticker(
      id: "JpH0zMx",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/JpH0zMx.png",
    ),
    Sticker(
      id: "uDkm7sT",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/uDkm7sT.png",
    ),
    Sticker(
      id: "oRXbUoW",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/oRXbUoW.png",
    ),
    Sticker(
      id: "Vvd9ZpL",
      type: "image/png",
      animated: false,
      width: 107,
      height: 80,
      link: "https://i.imgur.com/Vvd9ZpL.png",
    ),
    Sticker(
      id: "3SEbgch",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/3SEbgch.png",
    ),
    Sticker(
      id: "CRnKbj8",
      type: "image/png",
      animated: false,
      width: 87,
      height: 80,
      link: "https://i.imgur.com/CRnKbj8.png",
    ),
    Sticker(
      id: "kWtuEmE",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/kWtuEmE.png",
    ),
    Sticker(
      id: "j9EaYKZ",
      type: "image/png",
      animated: false,
      width: 85,
      height: 80,
      link: "https://i.imgur.com/j9EaYKZ.png",
    ),
    Sticker(
      id: "CcHxPhZ",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/CcHxPhZ.png",
    ),
    Sticker(
      id: "LQvVkiU",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/LQvVkiU.png",
    ),
    Sticker(
      id: "9yjx0SK",
      type: "image/png",
      animated: false,
      width: 90,
      height: 80,
      link: "https://i.imgur.com/9yjx0SK.png",
    ),
    Sticker(
      id: "B5VZU4W",
      type: "image/png",
      animated: false,
      width: 72,
      height: 80,
      link: "https://i.imgur.com/B5VZU4W.png",
    ),
    Sticker(
      id: "0V59s4Z",
      type: "image/png",
      animated: false,
      width: 85,
      height: 80,
      link: "https://i.imgur.com/0V59s4Z.png",
    ),
    Sticker(
      id: "Xl33sR6",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/Xl33sR6.png",
    ),
    Sticker(
      id: "Iui8bZ1",
      type: "image/png",
      animated: false,
      width: 114,
      height: 80,
      link: "https://i.imgur.com/Iui8bZ1.png",
    ),
    Sticker(
      id: "tZfEQAU",
      type: "image/png",
      animated: false,
      width: 82,
      height: 80,
      link: "https://i.imgur.com/tZfEQAU.png",
    ),
    Sticker(
      id: "6GZpfL4",
      type: "image/png",
      animated: false,
      width: 79,
      height: 80,
      link: "https://i.imgur.com/6GZpfL4.png",
    ),
    Sticker(
      id: "AmqUeZf",
      type: "image/png",
      animated: false,
      width: 97,
      height: 80,
      link: "https://i.imgur.com/AmqUeZf.png",
    ),
    Sticker(
      id: "A4kY8jD",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/A4kY8jD.png",
    ),
    Sticker(
      id: "3H5cKRI",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/3H5cKRI.png",
    ),
    Sticker(
      id: "nADIfiM",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/nADIfiM.png",
    ),
    Sticker(
      id: "Uk7S33l",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/Uk7S33l.png",
    ),
    Sticker(
      id: "EKsPa12",
      type: "image/png",
      animated: false,
      width: 72,
      height: 80,
      link: "https://i.imgur.com/EKsPa12.png",
    ),
    Sticker(
      id: "ujYvU1a",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/ujYvU1a.png",
    ),
    Sticker(
      id: "GC59UlU",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/GC59UlU.png",
    ),
    Sticker(
      id: "chO1jkK",
      type: "image/png",
      animated: false,
      width: 78,
      height: 80,
      link: "https://i.imgur.com/chO1jkK.png",
    ),
    Sticker(
      id: "UwaUyvZ",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/UwaUyvZ.png",
    ),
    Sticker(
      id: "fE8gqYO",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/fE8gqYO.png",
    ),
    Sticker(
      id: "SeaiFax",
      type: "image/png",
      animated: false,
      width: 70,
      height: 80,
      link: "https://i.imgur.com/SeaiFax.png",
    ),
    Sticker(
      id: "S4I3TIj",
      type: "image/png",
      animated: false,
      width: 113,
      height: 80,
      link: "https://i.imgur.com/S4I3TIj.png",
    ),
    Sticker(
      id: "3FTIGmx",
      type: "image/png",
      animated: false,
      width: 96,
      height: 80,
      link: "https://i.imgur.com/3FTIGmx.png",
    ),
    Sticker(
      id: "rPahHgD",
      type: "image/png",
      animated: false,
      width: 84,
      height: 80,
      link: "https://i.imgur.com/rPahHgD.png",
    ),
    Sticker(
      id: "8fj9xhw",
      type: "image/png",
      animated: false,
      width: 84,
      height: 80,
      link: "https://i.imgur.com/8fj9xhw.png",
    ),
    Sticker(
      id: "zoBvkY6",
      type: "image/png",
      animated: false,
      width: 108,
      height: 80,
      link: "https://i.imgur.com/zoBvkY6.png",
    ),
    Sticker(
      id: "O006sQ8",
      type: "image/png",
      animated: false,
      width: 70,
      height: 80,
      link: "https://i.imgur.com/O006sQ8.png",
    ),
    Sticker(
      id: "167U3tL",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/167U3tL.png",
    ),
    Sticker(
      id: "AFw4U4b",
      type: "image/png",
      animated: false,
      width: 118,
      height: 80,
      link: "https://i.imgur.com/AFw4U4b.png",
    ),
    Sticker(
      id: "EJfyRlW",
      type: "image/png",
      animated: false,
      width: 68,
      height: 80,
      link: "https://i.imgur.com/EJfyRlW.png",
    ),
    Sticker(
      id: "YecP8Hj",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/YecP8Hj.png",
    ),
    Sticker(
      id: "8hyII2K",
      type: "image/png",
      animated: false,
      width: 70,
      height: 80,
      link: "https://i.imgur.com/8hyII2K.png",
    ),
    Sticker(
      id: "ghH2nN7",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/ghH2nN7.png",
    ),
    Sticker(
      id: "IbavhqJ",
      type: "image/png",
      animated: false,
      width: 78,
      height: 80,
      link: "https://i.imgur.com/IbavhqJ.png",
    ),
    Sticker(
      id: "Un6Ie1n",
      type: "image/png",
      animated: false,
      width: 105,
      height: 80,
      link: "https://i.imgur.com/Un6Ie1n.png",
    ),
    Sticker(
      id: "lldMvfP",
      type: "image/png",
      animated: false,
      width: 85,
      height: 80,
      link: "https://i.imgur.com/lldMvfP.png",
    ),
    Sticker(
      id: "oGr0aVp",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/oGr0aVp.png",
    ),
    Sticker(
      id: "hRpp8ku",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/hRpp8ku.png",
    ),
    Sticker(
      id: "0CjC7JO",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/0CjC7JO.png",
    ),
    Sticker(
      id: "oXucvub",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/oXucvub.png",
    ),
    Sticker(
      id: "kzM7YTE",
      type: "image/png",
      animated: false,
      width: 67,
      height: 80,
      link: "https://i.imgur.com/kzM7YTE.png",
    ),
    Sticker(
      id: "cwckscq",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/cwckscq.png",
    ),
    Sticker(
      id: "CzhhRN2",
      type: "image/png",
      animated: false,
      width: 64,
      height: 80,
      link: "https://i.imgur.com/CzhhRN2.png",
    ),
    Sticker(
      id: "35Zg4Kq",
      type: "image/png",
      animated: false,
      width: 78,
      height: 80,
      link: "https://i.imgur.com/35Zg4Kq.png",
    ),
    Sticker(
      id: "IIhlsVE",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/IIhlsVE.png",
    ),
    Sticker(
      id: "7hpDwu8",
      type: "image/png",
      animated: false,
      width: 81,
      height: 80,
      link: "https://i.imgur.com/7hpDwu8.png",
    ),
    Sticker(
      id: "XEK0Z3h",
      type: "image/png",
      animated: false,
      width: 79,
      height: 80,
      link: "https://i.imgur.com/XEK0Z3h.png",
    ),
    Sticker(
      id: "ySwE87i",
      type: "image/png",
      animated: false,
      width: 84,
      height: 80,
      link: "https://i.imgur.com/ySwE87i.png",
    ),
    Sticker(
      id: "Tg0TcKA",
      type: "image/png",
      animated: false,
      width: 66,
      height: 80,
      link: "https://i.imgur.com/Tg0TcKA.png",
    ),
    Sticker(
      id: "iwIgekf",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/iwIgekf.png",
    ),
  ],
);
