import '../album_sticker.dart';
import '../sticker.dart';

const faceAlbum = AlbumSticker(
  id: "vmA0r",
  isDefault: true,
  stickers: [
    Sticker(
      id: "1xK3bm3",
      type: "image/png",
      animated: false,
      width: 40,
      height: 40,
      link: "https://i.imgur.com/1xK3bm3.png",
    ),
    Sticker(
      id: "kKcjmoH",
      type: "image/png",
      animated: false,
      width: 48,
      height: 48,
      link: "https://i.imgur.com/kKcjmoH.png",
    ),
    Sticker(
      id: "XGxqc0v",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/XGxqc0v.png",
    ),
    Sticker(
      id: "TyWzLOy",
      type: "image/png",
      animated: false,
      width: 45,
      height: 43,
      link: "https://i.imgur.com/TyWzLOy.png",
    ),
    Sticker(
      id: "YDKhOzM",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/YDKhOzM.png",
    ),
    Sticker(
      id: "AsBPJOY",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/AsBPJOY.png",
    ),
    Sticker(
      id: "Y9XGQJi",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/Y9XGQJi.png",
    ),
    Sticker(
      id: "Nf5AKDo",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/Nf5AKDo.png",
    ),
    Sticker(
      id: "ig3L68e",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/ig3L68e.png",
    ),
    Sticker(
      id: "jJnsOYE",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/jJnsOYE.png",
    ),
    Sticker(
      id: "7EsMbl4",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/7EsMbl4.png",
    ),
    Sticker(
      id: "IbCY3qj",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/IbCY3qj.png",
    ),
    Sticker(
      id: "MvkNYau",
      type: "image/png",
      animated: false,
      width: 49,
      height: 50,
      link: "https://i.imgur.com/MvkNYau.png",
    ),
    Sticker(
      id: "OREFWxo",
      type: "image/png",
      animated: false,
      width: 50,
      height: 46,
      link: "https://i.imgur.com/OREFWxo.png",
    ),
    Sticker(
      id: "ivdRT0P",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/ivdRT0P.png",
    ),
    Sticker(
      id: "cWAd7AE",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/cWAd7AE.png",
    ),
    Sticker(
      id: "cF0bg3R",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/cF0bg3R.png",
    ),
    Sticker(
      id: "Zqy0OHH",
      type: "image/png",
      animated: false,
      width: 50,
      height: 46,
      link: "https://i.imgur.com/Zqy0OHH.png",
    ),
    Sticker(
      id: "FP6jWNK",
      type: "image/png",
      animated: false,
      width: 49,
      height: 50,
      link: "https://i.imgur.com/FP6jWNK.png",
    ),
    Sticker(
      id: "IYqzj0A",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/IYqzj0A.png",
    ),
    Sticker(
      id: "SPFTNk5",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/SPFTNk5.png",
    ),
    Sticker(
      id: "3f2CyQU",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/3f2CyQU.png",
    ),
    Sticker(
      id: "mR7E4f6",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/mR7E4f6.png",
    ),
    Sticker(
      id: "O0w112T",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/O0w112T.png",
    ),
    Sticker(
      id: "ah2kzNK",
      type: "image/png",
      animated: false,
      width: 50,
      height: 47,
      link: "https://i.imgur.com/ah2kzNK.png",
    ),
    Sticker(
      id: "pQogsVq",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/pQogsVq.png",
    ),
    Sticker(
      id: "zcmUPkm",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/zcmUPkm.png",
    ),
    Sticker(
      id: "rc67JFX",
      type: "image/png",
      animated: false,
      width: 50,
      height: 48,
      link: "https://i.imgur.com/rc67JFX.png",
    ),
    Sticker(
      id: "1dBqJ50",
      type: "image/png",
      animated: false,
      width: 48,
      height: 50,
      link: "https://i.imgur.com/1dBqJ50.png",
    ),
    Sticker(
      id: "ZZTK17k",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/ZZTK17k.png",
    ),
    Sticker(
      id: "eDmLMZm",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/eDmLMZm.png",
    ),
    Sticker(
      id: "OZu3uOr",
      type: "image/png",
      animated: false,
      width: 50,
      height: 47,
      link: "https://i.imgur.com/OZu3uOr.png",
    ),
    Sticker(
      id: "ZhltM3Z",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/ZhltM3Z.png",
    ),
    Sticker(
      id: "xse3xLv",
      type: "image/png",
      animated: false,
      width: 50,
      height: 48,
      link: "https://i.imgur.com/xse3xLv.png",
    ),
    Sticker(
      id: "FDwXRyo",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/FDwXRyo.png",
    ),
    Sticker(
      id: "HPRNF0P",
      type: "image/png",
      animated: false,
      width: 50,
      height: 46,
      link: "https://i.imgur.com/HPRNF0P.png",
    ),
    Sticker(
      id: "ZQLQgoY",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/ZQLQgoY.png",
    ),
    Sticker(
      id: "DJk9Vzh",
      type: "image/png",
      animated: false,
      width: 43,
      height: 42,
      link: "https://i.imgur.com/DJk9Vzh.png",
    ),
    Sticker(
      id: "Ao5ktfU",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/Ao5ktfU.png",
    ),
    Sticker(
      id: "Q2b1ZyD",
      type: "image/png",
      animated: false,
      width: 48,
      height: 48,
      link: "https://i.imgur.com/Q2b1ZyD.png",
    ),
    Sticker(
      id: "wJ9R6PJ",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/wJ9R6PJ.png",
    ),
    Sticker(
      id: "m3SK4Uq",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/m3SK4Uq.png",
    ),
    Sticker(
      id: "trp5lFu",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/trp5lFu.png",
    ),
    Sticker(
      id: "yrZcJM4",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/yrZcJM4.png",
    ),
    Sticker(
      id: "o0jRUqa",
      type: "image/png",
      animated: false,
      width: 50,
      height: 43,
      link: "https://i.imgur.com/o0jRUqa.png",
    ),
    Sticker(
      id: "Jq2JMSx",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/Jq2JMSx.png",
    ),
    Sticker(
      id: "gwOs46F",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/gwOs46F.png",
    ),
    Sticker(
      id: "tC8WqCE",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/tC8WqCE.png",
    ),
    Sticker(
      id: "LnfESw2",
      type: "image/png",
      animated: false,
      width: 50,
      height: 47,
      link: "https://i.imgur.com/LnfESw2.png",
    ),
    Sticker(
      id: "LURMtFA",
      type: "image/gif",
      animated: true,
      width: 60,
      height: 60,
      link: "https://i.imgur.com/LURMtFA.gif",
    ),
    Sticker(
      id: "0TlCvUF",
      type: "image/png",
      animated: false,
      width: 67,
      height: 80,
      link: "https://i.imgur.com/0TlCvUF.png",
    ),
    Sticker(
      id: "m3zFCSU",
      type: "image/png",
      animated: false,
      width: 42,
      height: 40,
      link: "https://i.imgur.com/m3zFCSU.png",
    ),
    Sticker(
      id: "5jbUOur",
      type: "image/png",
      animated: false,
      width: 42,
      height: 41,
      link: "https://i.imgur.com/5jbUOur.png",
    ),
    Sticker(
      id: "TZ0qTj7",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/TZ0qTj7.png",
    ),
    Sticker(
      id: "XGCeq8F",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/XGCeq8F.png",
    ),
    Sticker(
      id: "jSxWffg",
      type: "image/png",
      animated: false,
      width: 39,
      height: 35,
      link: "https://i.imgur.com/jSxWffg.png",
    ),
    Sticker(
      id: "CNPdhfH",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/CNPdhfH.png",
    ),
    Sticker(
      id: "y4zPKnx",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/y4zPKnx.png",
    ),
    Sticker(
      id: "klLoCDO",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/klLoCDO.png",
    ),
    Sticker(
      id: "Qurh9ZX",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/Qurh9ZX.png",
    ),
    Sticker(
      id: "aROM8xD",
      type: "image/png",
      animated: false,
      width: 50,
      height: 48,
      link: "https://i.imgur.com/aROM8xD.png",
    ),
    Sticker(
      id: "zovduCt",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/zovduCt.png?1",
    ),
    Sticker(
      id: "tMFhUIC",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/tMFhUIC.png",
    ),
    Sticker(
      id: "lIIrwJl",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/lIIrwJl.png",
    ),
    Sticker(
      id: "ZgYw3c4",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/ZgYw3c4.png",
    ),
    Sticker(
      id: "lMp8rQq",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/lMp8rQq.png",
    ),
    Sticker(
      id: "NgXQvCc",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/NgXQvCc.png",
    ),
    Sticker(
      id: "Uhcne0U",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/Uhcne0U.png",
    ),
    Sticker(
      id: "HSxdICL",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/HSxdICL.png",
    ),
    Sticker(
      id: "SDlpC0Y",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/SDlpC0Y.png",
    ),
    Sticker(
      id: "y48ZC1z",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/y48ZC1z.png",
    ),
    Sticker(
      id: "HFkdT2a",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/HFkdT2a.png",
    ),
    Sticker(
      id: "ekx9lCr",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/ekx9lCr.png",
    ),
    Sticker(
      id: "8PoJAIg",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/8PoJAIg.png",
    ),
    Sticker(
      id: "aCQz1CN",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/aCQz1CN.png",
    ),
    Sticker(
      id: "oKHo50a",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/oKHo50a.png",
    ),
    Sticker(
      id: "7RHhhXz",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/7RHhhXz.png",
    ),
    Sticker(
      id: "yyGhRVo",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/yyGhRVo.png",
    ),
    Sticker(
      id: "tpM55MI",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/tpM55MI.png",
    ),
    Sticker(
      id: "uNTPrw5",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/uNTPrw5.png",
    ),
    Sticker(
      id: "DtT78SF",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/DtT78SF.png",
    ),
    Sticker(
      id: "pVPl8r6",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/pVPl8r6.png",
    ),
    Sticker(
      id: "9WvHKzw",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/9WvHKzw.png",
    ),
    Sticker(
      id: "xNimagf",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/xNimagf.png",
    ),
    Sticker(
      id: "YRsvqtB",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/YRsvqtB.png?1",
    ),
    Sticker(
      id: "XIm44Bf",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/XIm44Bf.png",
    ),
    Sticker(
      id: "TavJsAJ",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/TavJsAJ.png",
    ),
    Sticker(
      id: "IcqtHI8",
      type: "image/gif",
      animated: true,
      width: 48,
      height: 36,
      link: "https://i.imgur.com/IcqtHI8.gif",
    ),
    Sticker(
      id: "LfiFyCB",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/LfiFyCB.png",
    ),
    Sticker(
      id: "EpLgxwA",
      type: "image/gif",
      animated: true,
      width: 60,
      height: 60,
      link: "https://i.imgur.com/EpLgxwA.gif",
    ),
    Sticker(
      id: "fN5fRLD",
      type: "image/gif",
      animated: true,
      width: 60,
      height: 60,
      link: "https://i.imgur.com/fN5fRLD.gif",
    ),
    Sticker(
      id: "jk0S9Mk",
      type: "image/png",
      animated: false,
      width: 50,
      height: 35,
      link: "https://i.imgur.com/jk0S9Mk.png",
    ),
    Sticker(
      id: "pEDsN4Y",
      type: "image/png",
      animated: false,
      width: 48,
      height: 50,
      link: "https://i.imgur.com/pEDsN4Y.png",
    ),
    Sticker(
      id: "mjv8Ias",
      type: "image/png",
      animated: false,
      width: 50,
      height: 48,
      link: "https://i.imgur.com/mjv8Ias.png",
    ),
    Sticker(
      id: "QcHztvg",
      type: "image/png",
      animated: false,
      width: 50,
      height: 45,
      link: "https://i.imgur.com/QcHztvg.png",
    ),
    Sticker(
      id: "mRY9rMn",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/mRY9rMn.png",
    ),
    Sticker(
      id: "TUGinn4",
      type: "image/png",
      animated: false,
      width: 48,
      height: 50,
      link: "https://i.imgur.com/TUGinn4.png",
    ),
    Sticker(
      id: "dRd4c58",
      type: "image/png",
      animated: false,
      width: 60,
      height: 60,
      link: "https://i.imgur.com/dRd4c58.png",
    ),
    Sticker(
      id: "zfZheUX",
      type: "image/png",
      animated: false,
      width: 70,
      height: 68,
      link: "https://i.imgur.com/zfZheUX.png",
    ),
    Sticker(
      id: "PsZ4AFL",
      type: "image/png",
      animated: false,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/PsZ4AFL.png",
    ),
    Sticker(
      id: "kdp9k8K",
      type: "image/png",
      animated: false,
      width: 98,
      height: 100,
      link: "https://i.imgur.com/kdp9k8K.png",
    ),
    Sticker(
      id: "OJZUj1K",
      type: "image/png",
      animated: false,
      width: 98,
      height: 100,
      link: "https://i.imgur.com/OJZUj1K.png",
    ),
    Sticker(
      id: "5Mhxch1",
      type: "image/png",
      animated: false,
      width: 48,
      height: 30,
      link: "https://i.imgur.com/5Mhxch1.png?1",
    ),
    Sticker(
      id: "uak2yld",
      type: "image/gif",
      animated: true,
      width: 40,
      height: 40,
      link: "https://i.imgur.com/uak2yld.gif",
    ),
    Sticker(
      id: "0E9MbLZ",
      type: "image/gif",
      animated: true,
      width: 215,
      height: 155,
      link: "https://i.imgur.com/0E9MbLZ.gif",
    ),
    Sticker(
      id: "oO2JmQu",
      type: "image/gif",
      animated: true,
      width: 39,
      height: 48,
      link: "https://i.imgur.com/oO2JmQu.gif",
    ),
    Sticker(
      id: "xb3ztaa",
      type: "image/gif",
      animated: true,
      width: 49,
      height: 60,
      link: "https://i.imgur.com/xb3ztaa.gif",
    ),
    Sticker(
      id: "uMJ2VAm",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/uMJ2VAm.gif",
    ),
    Sticker(
      id: "8JMEFZ5",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/8JMEFZ5.gif",
    ),
    Sticker(
      id: "duAr1BH",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/duAr1BH.gif",
    ),
    Sticker(
      id: "6R4FDwM",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/6R4FDwM.gif",
    ),
    Sticker(
      id: "b4H86RM",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/b4H86RM.gif",
    ),
    Sticker(
      id: "6VUIcSx",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/6VUIcSx.gif",
    ),
    Sticker(
      id: "PgAlURZ",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/PgAlURZ.gif",
    ),
    Sticker(
      id: "s4JOmFt",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/s4JOmFt.gif",
    ),
    Sticker(
      id: "chFqDUl",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/chFqDUl.gif",
    ),
    Sticker(
      id: "YAqxQl7",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/YAqxQl7.gif",
    ),
    Sticker(
      id: "nsZd0F5",
      type: "image/gif",
      animated: true,
      width: 50,
      height: 50,
      link: "https://i.imgur.com/nsZd0F5.gif",
    ),
  ],
);
