import '../album_sticker.dart';
import '../sticker.dart';

const mcAlbum = AlbumSticker(
  id: "2GeYfEu",
  isDefault: true,
  stickers: [
    Sticker(
      id: "rJrD7d6",
      type: "image/png",
      animated: false,
      width: 126,
      height: 105,
      link: "https://i.imgur.com/rJrD7d6.png",
    ),
    Sticker(
      id: "DKHRJ0q",
      type: "image/png",
      animated: false,
      width: 100,
      height: 110,
      link: "https://i.imgur.com/DKHRJ0q.png",
    ),
    Sticker(
      id: "B6VHQ73",
      type: "image/png",
      animated: false,
      width: 125,
      height: 105,
      link: "https://i.imgur.com/B6VHQ73.png",
    ),
    Sticker(
      id: "MwRP1Lx",
      type: "image/png",
      animated: false,
      width: 128,
      height: 90,
      link: "https://i.imgur.com/MwRP1Lx.png",
    ),
    Sticker(
      id: "DLAFXAq",
      type: "image/png",
      animated: false,
      width: 145,
      height: 104,
      link: "https://i.imgur.com/DLAFXAq.png",
    ),
    Sticker(
      id: "w4jOcMU",
      type: "image/png",
      animated: false,
      width: 110,
      height: 100,
      link: "https://i.imgur.com/w4jOcMU.png",
    ),
    Sticker(
      id: "lb10GCx",
      type: "image/png",
      animated: false,
      width: 111,
      height: 106,
      link: "https://i.imgur.com/lb10GCx.png",
    ),
    Sticker(
      id: "QMSjhid",
      type: "image/png",
      animated: false,
      width: 120,
      height: 104,
      link: "https://i.imgur.com/QMSjhid.png",
    ),
    Sticker(
      id: "6GSV5qI",
      type: "image/png",
      animated: false,
      width: 117,
      height: 101,
      link: "https://i.imgur.com/6GSV5qI.png",
    ),
    Sticker(
      id: "dd0V7vl",
      type: "image/png",
      animated: false,
      width: 110,
      height: 110,
      link: "https://i.imgur.com/dd0V7vl.png",
    ),
    Sticker(
      id: "8qdA8EL",
      type: "image/png",
      animated: false,
      width: 128,
      height: 110,
      link: "https://i.imgur.com/8qdA8EL.png",
    ),
    Sticker(
      id: "42LD30o",
      type: "image/png",
      animated: false,
      width: 128,
      height: 110,
      link: "https://i.imgur.com/42LD30o.png",
    ),
    Sticker(
      id: "gzO4Eu2",
      type: "image/png",
      animated: false,
      width: 100,
      height: 110,
      link: "https://i.imgur.com/gzO4Eu2.png",
    ),
    Sticker(
      id: "vGengAv",
      type: "image/png",
      animated: false,
      width: 100,
      height: 110,
      link: "https://i.imgur.com/vGengAv.png",
    ),
    Sticker(
      id: "eTgoguo",
      type: "image/png",
      animated: false,
      width: 128,
      height: 110,
      link: "https://i.imgur.com/eTgoguo.png",
    ),
    Sticker(
      id: "A1wzNCp",
      type: "image/png",
      animated: false,
      width: 130,
      height: 105,
      link: "https://i.imgur.com/A1wzNCp.png",
    ),
    Sticker(
      id: "UKJvgEO",
      type: "image/png",
      animated: false,
      width: 120,
      height: 103,
      link: "https://i.imgur.com/UKJvgEO.png",
    ),
    Sticker(
      id: "SPBoQ9S",
      type: "image/png",
      animated: false,
      width: 120,
      height: 103,
      link: "https://i.imgur.com/SPBoQ9S.png",
    ),
    Sticker(
      id: "WqGFpia",
      type: "image/png",
      animated: false,
      width: 132,
      height: 114,
      link: "https://i.imgur.com/WqGFpia.png",
    ),
    Sticker(
      id: "9eUGZpZ",
      type: "image/png",
      animated: false,
      width: 120,
      height: 103,
      link: "https://i.imgur.com/9eUGZpZ.png",
    ),
    Sticker(
      id: "gfQUXz9",
      type: "image/png",
      animated: false,
      width: 100,
      height: 105,
      link: "https://i.imgur.com/gfQUXz9.png",
    ),
    Sticker(
      id: "wB8ANsQ",
      type: "image/png",
      animated: false,
      width: 120,
      height: 100,
      link: "https://i.imgur.com/wB8ANsQ.png",
    ),
    Sticker(
      id: "YFx7RQm",
      type: "image/png",
      animated: false,
      width: 120,
      height: 100,
      link: "https://i.imgur.com/YFx7RQm.png",
    ),
    Sticker(
      id: "s48INZX",
      type: "image/png",
      animated: false,
      width: 80,
      height: 80,
      link: "https://i.imgur.com/s48INZX.png",
    ),
    Sticker(
      id: "Et0cnz7",
      type: "image/png",
      animated: false,
      width: 128,
      height: 107,
      link: "https://i.imgur.com/Et0cnz7.png",
    ),
    Sticker(
      id: "7XRxntq",
      type: "image/png",
      animated: false,
      width: 116,
      height: 99,
      link: "https://i.imgur.com/7XRxntq.png",
    ),
    Sticker(
      id: "OZLq6mp",
      type: "image/png",
      animated: false,
      width: 115,
      height: 104,
      link: "https://i.imgur.com/OZLq6mp.png",
    ),
    Sticker(
      id: "EYM94ID",
      type: "image/png",
      animated: false,
      width: 120,
      height: 113,
      link: "https://i.imgur.com/EYM94ID.png",
    ),
    Sticker(
      id: "TXtc36K",
      type: "image/png",
      animated: false,
      width: 141,
      height: 103,
      link: "https://i.imgur.com/TXtc36K.png",
    ),
    Sticker(
      id: "WltlHmr",
      type: "image/png",
      animated: false,
      width: 110,
      height: 100,
      link: "https://i.imgur.com/WltlHmr.png",
    ),
    Sticker(
      id: "PSr6iPW",
      type: "image/png",
      animated: false,
      width: 98,
      height: 98,
      link: "https://i.imgur.com/PSr6iPW.png",
    ),
    Sticker(
      id: "qAKVVIn",
      type: "image/png",
      animated: false,
      width: 122,
      height: 105,
      link: "https://i.imgur.com/qAKVVIn.png",
    ),
    Sticker(
      id: "28b13Tg",
      type: "image/png",
      animated: false,
      width: 103,
      height: 106,
      link: "https://i.imgur.com/28b13Tg.png",
    ),
    Sticker(
      id: "DDb2PmF",
      type: "image/png",
      animated: false,
      width: 116,
      height: 99,
      link: "https://i.imgur.com/DDb2PmF.png",
    ),
    Sticker(
      id: "i51KHm4",
      type: "image/png",
      animated: false,
      width: 116,
      height: 115,
      link: "https://i.imgur.com/i51KHm4.png",
    ),
    Sticker(
      id: "7VpRxek",
      type: "image/png",
      animated: false,
      width: 117,
      height: 101,
      link: "https://i.imgur.com/7VpRxek.png",
    ),
    Sticker(
      id: "x5FEF3u",
      type: "image/png",
      animated: false,
      width: 122,
      height: 109,
      link: "https://i.imgur.com/x5FEF3u.png",
    ),
    Sticker(
      id: "ULwaIDg",
      type: "image/png",
      animated: false,
      width: 117,
      height: 101,
      link: "https://i.imgur.com/ULwaIDg.png",
    ),
    Sticker(
      id: "rqVyJSd",
      type: "image/png",
      animated: false,
      width: 122,
      height: 106,
      link: "https://i.imgur.com/rqVyJSd.png",
    ),
    Sticker(
      id: "xpRZZUp",
      type: "image/png",
      animated: false,
      width: 118,
      height: 102,
      link: "https://i.imgur.com/xpRZZUp.png",
    ),
    Sticker(
      id: "UgxIOqI",
      type: "image/png",
      animated: false,
      width: 120,
      height: 100,
      link: "https://i.imgur.com/UgxIOqI.png",
    ),
    Sticker(
      id: "Xti1EX6",
      type: "image/png",
      animated: false,
      width: 120,
      height: 100,
      link: "https://i.imgur.com/Xti1EX6.png",
    ),
    Sticker(
      id: "txzaItP",
      type: "image/png",
      animated: false,
      width: 109,
      height: 102,
      link: "https://i.imgur.com/txzaItP.png",
    ),
    Sticker(
      id: "T9BOdYs",
      type: "image/png",
      animated: false,
      width: 175,
      height: 100,
      link: "https://i.imgur.com/T9BOdYs.png",
    ),
    Sticker(
      id: "EMPmf1l",
      type: "image/png",
      animated: false,
      width: 142,
      height: 102,
      link: "https://i.imgur.com/EMPmf1l.png",
    ),
    Sticker(
      id: "ZZfk0Pa",
      type: "image/png",
      animated: false,
      width: 137,
      height: 107,
      link: "https://i.imgur.com/ZZfk0Pa.png",
    ),
    Sticker(
      id: "nexKVlD",
      type: "image/png",
      animated: false,
      width: 130,
      height: 100,
      link: "https://i.imgur.com/nexKVlD.png",
    ),
    Sticker(
      id: "dJ4Tz8i",
      type: "image/png",
      animated: false,
      width: 129,
      height: 106,
      link: "https://i.imgur.com/dJ4Tz8i.png",
    ),
    Sticker(
      id: "8ZmwPPq",
      type: "image/png",
      animated: false,
      width: 125,
      height: 103,
      link: "https://i.imgur.com/8ZmwPPq.png",
    ),
    Sticker(
      id: "pzgvZM4",
      type: "image/png",
      animated: false,
      width: 105,
      height: 105,
      link: "https://i.imgur.com/pzgvZM4.png",
    ),
    Sticker(
      id: "RBip2HU",
      type: "image/png",
      animated: false,
      width: 115,
      height: 101,
      link: "https://i.imgur.com/RBip2HU.png",
    ),
    Sticker(
      id: "WhmdtDW",
      type: "image/png",
      animated: false,
      width: 128,
      height: 107,
      link: "https://i.imgur.com/WhmdtDW.png",
    ),
    Sticker(
      id: "SlDvzBY",
      type: "image/png",
      animated: false,
      width: 130,
      height: 100,
      link: "https://i.imgur.com/SlDvzBY.png",
    ),
    Sticker(
      id: "Wv2IyDJ",
      type: "image/png",
      animated: false,
      width: 115,
      height: 100,
      link: "https://i.imgur.com/Wv2IyDJ.png",
    ),
    Sticker(
      id: "IDYwpJQ",
      type: "image/png",
      animated: false,
      width: 125,
      height: 105,
      link: "https://i.imgur.com/IDYwpJQ.png",
    ),
    Sticker(
      id: "2Cd8Oj9",
      type: "image/png",
      animated: false,
      width: 103,
      height: 106,
      link: "https://i.imgur.com/2Cd8Oj9.png",
    ),
    Sticker(
      id: "tEXZKhU",
      type: "image/png",
      animated: false,
      width: 130,
      height: 112,
      link: "https://i.imgur.com/tEXZKhU.png",
    ),
    Sticker(
      id: "dTYwdqI",
      type: "image/png",
      animated: false,
      width: 117,
      height: 101,
      link: "https://i.imgur.com/dTYwdqI.png",
    ),
    Sticker(
      id: "BJT0Sx4",
      type: "image/png",
      animated: false,
      width: 113,
      height: 111,
      link: "https://i.imgur.com/BJT0Sx4.png",
    ),
    Sticker(
      id: "RKUdYn3",
      type: "image/png",
      animated: false,
      width: 158,
      height: 132,
      link: "https://i.imgur.com/RKUdYn3.png",
    ),
    Sticker(
      id: "VreTurp",
      type: "image/png",
      animated: false,
      width: 105,
      height: 112,
      link: "https://i.imgur.com/VreTurp.png",
    ),
    Sticker(
      id: "p5hC6Ox",
      type: "image/png",
      animated: false,
      width: 118,
      height: 102,
      link: "https://i.imgur.com/p5hC6Ox.png",
    ),
    Sticker(
      id: "jseat8O",
      type: "image/png",
      animated: false,
      width: 96,
      height: 106,
      link: "https://i.imgur.com/jseat8O.png",
    ),
    Sticker(
      id: "dDlJ9C0",
      type: "image/png",
      animated: false,
      width: 96,
      height: 106,
      link: "https://i.imgur.com/dDlJ9C0.png",
    ),
    Sticker(
      id: "MRy0lJ2",
      type: "image/png",
      animated: false,
      width: 96,
      height: 106,
      link: "https://i.imgur.com/MRy0lJ2.png",
    ),
    Sticker(
      id: "goOtIG6",
      type: "image/png",
      animated: false,
      width: 114,
      height: 106,
      link: "https://i.imgur.com/goOtIG6.png",
    ),
    Sticker(
      id: "EhjDcV1",
      type: "image/png",
      animated: false,
      width: 130,
      height: 104,
      link: "https://i.imgur.com/EhjDcV1.png",
    ),
    Sticker(
      id: "lLcWkNw",
      type: "image/png",
      animated: false,
      width: 126,
      height: 105,
      link: "https://i.imgur.com/lLcWkNw.png",
    ),
    Sticker(
      id: "eA3Yaym",
      type: "image/png",
      animated: false,
      width: 130,
      height: 100,
      link: "https://i.imgur.com/eA3Yaym.png",
    ),
    Sticker(
      id: "9TpWCTp",
      type: "image/png",
      animated: false,
      width: 120,
      height: 100,
      link: "https://i.imgur.com/9TpWCTp.png",
    ),
    Sticker(
      id: "5bNAAJx",
      type: "image/png",
      animated: false,
      width: 128,
      height: 111,
      link: "https://i.imgur.com/5bNAAJx.png",
    ),
    Sticker(
      id: "Sl6fs7K",
      type: "image/png",
      animated: false,
      width: 119,
      height: 106,
      link: "https://i.imgur.com/Sl6fs7K.png",
    ),
    Sticker(
      id: "RwpUF2d",
      type: "image/png",
      animated: false,
      width: 115,
      height: 105,
      link: "https://i.imgur.com/RwpUF2d.png",
    ),
    Sticker(
      id: "KD1dNZA",
      type: "image/png",
      animated: false,
      width: 117,
      height: 101,
      link: "https://i.imgur.com/KD1dNZA.png",
    ),
    Sticker(
      id: "HaZ5oGg",
      type: "image/png",
      animated: false,
      width: 128,
      height: 111,
      link: "https://i.imgur.com/HaZ5oGg.png",
    ),
    Sticker(
      id: "1Pgfy7S",
      type: "image/png",
      animated: false,
      width: 130,
      height: 112,
      link: "https://i.imgur.com/1Pgfy7S.png",
    ),
    Sticker(
      id: "s4dv5Ge",
      type: "image/png",
      animated: false,
      width: 110,
      height: 102,
      link: "https://i.imgur.com/s4dv5Ge.png",
    ),
    Sticker(
      id: "Brqr04u",
      type: "image/png",
      animated: false,
      width: 120,
      height: 103,
      link: "https://i.imgur.com/Brqr04u.png",
    ),
    Sticker(
      id: "21xiTfW",
      type: "image/png",
      animated: false,
      width: 130,
      height: 112,
      link: "https://i.imgur.com/21xiTfW.png",
    ),
    Sticker(
      id: "yedYLxz",
      type: "image/png",
      animated: false,
      width: 130,
      height: 112,
      link: "https://i.imgur.com/yedYLxz.png",
    ),
    Sticker(
      id: "fUBwVZ0",
      type: "image/png",
      animated: false,
      width: 125,
      height: 103,
      link: "https://i.imgur.com/fUBwVZ0.png",
    ),
    Sticker(
      id: "5KLnOAb",
      type: "image/png",
      animated: false,
      width: 126,
      height: 105,
      link: "https://i.imgur.com/5KLnOAb.png",
    ),
    Sticker(
      id: "dW8GpCs",
      type: "image/png",
      animated: false,
      width: 120,
      height: 100,
      link: "https://i.imgur.com/dW8GpCs.png",
    ),
    Sticker(
      id: "FNkGe15",
      type: "image/png",
      animated: false,
      width: 130,
      height: 106,
      link: "https://i.imgur.com/FNkGe15.png",
    ),
    Sticker(
      id: "O1tLIGM",
      type: "image/png",
      animated: false,
      width: 130,
      height: 106,
      link: "https://i.imgur.com/O1tLIGM.png",
    ),
    Sticker(
      id: "UePl9eb",
      type: "image/png",
      animated: false,
      width: 130,
      height: 106,
      link: "https://i.imgur.com/UePl9eb.png",
    ),
    Sticker(
      id: "cu4mWuQ",
      type: "image/png",
      animated: false,
      width: 125,
      height: 100,
      link: "https://i.imgur.com/cu4mWuQ.png",
    ),
    Sticker(
      id: "74Hdu6e",
      type: "image/png",
      animated: false,
      width: 120,
      height: 103,
      link: "https://i.imgur.com/74Hdu6e.png",
    ),
    Sticker(
      id: "AmScAn0",
      type: "image/png",
      animated: false,
      width: 90,
      height: 115,
      link: "https://i.imgur.com/AmScAn0.png",
    ),
    Sticker(
      id: "6aZUoR3",
      type: "image/png",
      animated: false,
      width: 100,
      height: 100,
      link: "https://i.imgur.com/6aZUoR3.png",
    ),
    Sticker(
      id: "aHDbeAC",
      type: "image/png",
      animated: false,
      width: 128,
      height: 110,
      link: "https://i.imgur.com/aHDbeAC.png",
    ),
    Sticker(
      id: "vDv3hRD",
      type: "image/png",
      animated: false,
      width: 100,
      height: 100,
      link: "https://i.imgur.com/vDv3hRD.png",
    ),
    Sticker(
      id: "b3gH9gP",
      type: "image/png",
      animated: false,
      width: 128,
      height: 107,
      link: "https://i.imgur.com/b3gH9gP.png",
    ),
    Sticker(
      id: "EyWuGwP",
      type: "image/png",
      animated: false,
      width: 100,
      height: 100,
      link: "https://i.imgur.com/EyWuGwP.png",
    ),
    Sticker(
      id: "TBZcPuq",
      type: "image/png",
      animated: false,
      width: 120,
      height: 100,
      link: "https://i.imgur.com/TBZcPuq.png",
    ),
    Sticker(
      id: "XSChLtR",
      type: "image/png",
      animated: false,
      width: 126,
      height: 105,
      link: "https://i.imgur.com/XSChLtR.png",
    ),
    Sticker(
      id: "b9K4jp0",
      type: "image/png",
      animated: false,
      width: 130,
      height: 100,
      link: "https://i.imgur.com/b9K4jp0.png",
    ),
    Sticker(
      id: "vv3YYUH",
      type: "image/png",
      animated: false,
      width: 120,
      height: 102,
      link: "https://i.imgur.com/vv3YYUH.png",
    ),
    Sticker(
      id: "BulZuba",
      type: "image/png",
      animated: false,
      width: 120,
      height: 103,
      link: "https://i.imgur.com/BulZuba.png",
    ),
    Sticker(
      id: "p4LkamB",
      type: "image/png",
      animated: false,
      width: 128,
      height: 107,
      link: "https://i.imgur.com/p4LkamB.png",
    ),
    Sticker(
      id: "kPWUHov",
      type: "image/png",
      animated: false,
      width: 140,
      height: 109,
      link: "https://i.imgur.com/kPWUHov.png",
    ),
    Sticker(
      id: "EruifKI",
      type: "image/png",
      animated: false,
      width: 128,
      height: 111,
      link: "https://i.imgur.com/EruifKI.png",
    ),
    Sticker(
      id: "NuBTHZJ",
      type: "image/png",
      animated: false,
      width: 128,
      height: 111,
      link: "https://i.imgur.com/NuBTHZJ.png",
    ),
    Sticker(
      id: "2eBwGpU",
      type: "image/png",
      animated: false,
      width: 128,
      height: 104,
      link: "https://i.imgur.com/2eBwGpU.png",
    ),
    Sticker(
      id: "nxT3llI",
      type: "image/png",
      animated: false,
      width: 128,
      height: 104,
      link: "https://i.imgur.com/nxT3llI.png",
    ),
    Sticker(
      id: "lE1jXU2",
      type: "image/png",
      animated: false,
      width: 100,
      height: 110,
      link: "https://i.imgur.com/lE1jXU2.png",
    ),
    Sticker(
      id: "PNDdMei",
      type: "image/png",
      animated: false,
      width: 155,
      height: 108,
      link: "https://i.imgur.com/PNDdMei.png",
    ),
  ],
);
