import '../album_sticker.dart';
import '../sticker.dart';

const twoCatsAlbum = AlbumSticker(
  id: "dpWZZB0",
  isDefault: true,
  stickers: [
    Sticker(
      id: "PcZoVQj",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/PcZoVQj.gif",
    ),
    Sticker(
      id: "Orf3rSW",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/Orf3rSW.gif",
    ),
    Sticker(
      id: "UtBDn9a",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/UtBDn9a.gif",
    ),
    Sticker(
      id: "tnO1bUC",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/tnO1bUC.gif",
    ),
    Sticker(
      id: "L3PJKQK",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/L3PJKQK.gif",
    ),
    Sticker(
      id: "Ngxjmqc",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/Ngxjmqc.gif",
    ),
    Sticker(
      id: "4b24yKJ",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/4b24yKJ.gif",
    ),
    Sticker(
      id: "DRwkswV",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/DRwkswV.gif",
    ),
    Sticker(
      id: "aJ10nnd",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/aJ10nnd.gif",
    ),
    Sticker(
      id: "ZMwethB",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/ZMwethB.gif",
    ),
    Sticker(
      id: "ebrpwxJ",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/ebrpwxJ.gif",
    ),
    Sticker(
      id: "9pJqjrI",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/9pJqjrI.gif",
    ),
    Sticker(
      id: "UZVg1F5",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/UZVg1F5.gif",
    ),
    Sticker(
      id: "VVxAtCM",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/VVxAtCM.gif",
    ),
    Sticker(
      id: "N4RawBT",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/N4RawBT.gif",
    ),
    Sticker(
      id: "mZK7h6Z",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/mZK7h6Z.gif",
    ),
    Sticker(
      id: "p6cee3p",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/p6cee3p.gif",
    ),
    Sticker(
      id: "LbCe3Og",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/LbCe3Og.gif",
    ),
    Sticker(
      id: "utPkTTM",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/utPkTTM.gif",
    ),
    Sticker(
      id: "XG3E6Lb",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/XG3E6Lb.gif",
    ),
    Sticker(
      id: "RxUWS4L",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/RxUWS4L.gif",
    ),
    Sticker(
      id: "8IATBpV",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/8IATBpV.gif",
    ),
    Sticker(
      id: "3mzhhqU",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/3mzhhqU.gif",
    ),
    Sticker(
      id: "m6ztNII",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/m6ztNII.gif",
    ),
    Sticker(
      id: "MnTrg0L",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/MnTrg0L.gif",
    ),
    Sticker(
      id: "azxKpTB",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/azxKpTB.gif",
    ),
    Sticker(
      id: "raMM6BX",
      type: "image/gif",
      animated: true,
      width: 128,
      height: 128,
      link: "https://i.imgur.com/raMM6BX.gif",
    ),
  ],
);
